version: "3"

services:
    app:
      build:
        context: webapp
        dockerfile: Dockerfile
      ports: ["8080:8080"]
      volumes:
      - $PWD/:/app
    solr:
      build:
        context: .
      ports: ["8983:8983"]